name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy-badminton:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /home/ec2-user/projects/python/badminton-scoreboard
          git reset --hard HEAD
          git pull origin master
          source venv/bin/activate
          pip install -r requirements.txt
          deactivate
          sudo systemctl restart badminton-scoreboard
